repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml


  - repo: https://github.com/psf/black
    rev: 24.1.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=120
        exclude: '(venv|\.venv|__pycache__|migrations|db\.sqlite3|\.git)'

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args:
          - --profile=black
          - --skip=venv
          - --skip=.venv
          - --skip=__pycache__
          - --skip=migrations
          - --skip=db.sqlite3

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        exclude: '(venv|\.venv|__pycache__|migrations|db\.sqlite3|\.git)'

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: bandit security check
        args:
          - -r
          - app/
          - -f
          - json
        files: ^app/
        additional_dependencies: [ pbr ]
        pass_filenames: false
        exclude: '(venv|\.venv|__pycache__|migrations|db\.sqlite3|\.git)'
